sudo: false
language: erlang
otp_release: R16B03-1
python: 2.7
addons:
  apt:
    packages:
      - bluez
      - libbluetooth-dev
before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install -r requirements.txt --user `whoami`
script: "make ci"
after_failure: "echo 'logs/raw.log\n'; cat logs/raw.log; for f in `find logs/ct_run*/log*/ -type f`; do echo \"\n$f\n\" ; cat $f; done"